const CONFIG = {
  SUPABASE_URL: 'https://eugoseuulbikgohksxiw.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1Z29zZXV1bGJpa2dvaGtzeGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4OTU2NzUsImV4cCI6MjEwMDQ3MTY3NX0.hwztwW2iqsTN8ppQplgHTCy2mktk_IFWEiTXSw6O6bM',

  PLACES_API_KEY: 'AIzaSyDxYqya6fC7dUbW5PpjRoYeh9jvvSDQxVk',

  RECOMMENDED_MIN_RATING: 4.3,
  RECOMMENDED_MIN_REVIEWS: 30,
  ISLAND_BOX_PADDING_DEG: 0.02,
  MAX_PAGES_PER_QUERY: 3,

  ARRIVALS_WINDOW_DAYS: 60,
};
